apiVersion: v1
kind: Secret
metadata:
  name: gitops-repo-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  url: aHR0cHM6Ly9naXRodWIuY29tL0JIVFMtUXVhZE9wcy9naXRvcHMtcmVwbw==
  username: Thanyani266
  password: eW91cl9hY3R1YWxfdXNlcm5hbWU=