apiVersion: ENC[AES256_GCM,data:duE=,iv:azlQ7WHyyPtXMx5+BX8lcOwdna1mgrUgEhm2SuY/FA8=,tag:xRMqkRe2KdPa21GCiirPmA==,type:str]
kind: ENC[AES256_GCM,data:UKYoiCQv,iv:V3qwXH5yQXSF2gKl182lEDAbIj4FBcl0DKyugPCjGbQ=,tag:VNWJzkImzHCngS2zkCmcUw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:S1GicPNcCaAprEP2N88=,iv:4kAurd700FMrBCq0qQMrfCckwXzD1lywpqP4hvPe20w=,tag:x5RdL4av76Kn7laraa+6bA==,type:str]
type: ENC[AES256_GCM,data:+5wwGA6k,iv:JtsJ9YY60+jJOpenoRT0TLDDcMTCcIg/hi1xpW5h5lY=,tag:a1xn9LGTpQm8tRv7rFZJ6Q==,type:str]
stringData:
    SPRING_DATASOURCE_URL: ENC[AES256_GCM,data:ITO4/hY1T3LfHaiJfHMM/LNDuTljjPcZloO0mKsvGI9mIQ/buGugmSOfNjt/EOC+PCT+r2PgrliGSuClDhBdt+8=,iv:obIt73D8CoNjFk0QHQCRJ10ryYXMtxcyADSfMSWLzuY=,tag:eYvD1QGSc3pMQo791fXpBw==,type:str]
    SPRING_DATASOURCE_USERNAME: ENC[AES256_GCM,data:tAiMAw==,iv:cqvpztsmyd7qljlMZ94Hd0F0axNc94MceSeHLtfqB2k=,tag:LWjYDQbXBJp90TU1NBYfvA==,type:str]
    SPRING_DATASOURCE_PASSWORD: ENC[AES256_GCM,data:+0Kzin5i,iv:NtINc9GcsMObtnWeq3ktl9BKvx9t30zBLPxACR5MDBs=,tag:NyZYwuRhSHprWcHYbgzWZA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:39ZWjlV+p47gW08l19KlKoK6GfjXCPzF46uWMFwDyqNAuMtWoXdf5OgB+l9Nr9pVKxxrq2plaITeAHLvYkrq5qg=,iv:/vYIFxp7Uf5VqVTBp1MY0Ea+n4gNKcRrQdETSHC5su0=,tag:tJlpMJ5lCMI9Zer3S2ZbLg==,type:str]
    JWT_EXPIRATION_MS: ENC[AES256_GCM,data:LY7CCi0l+X8=,iv:8WllgDLd/O0jASG62tk+R3xNG9hgpb1OXcdSfWxJOm8=,tag:K/F/TYO/jrwf3r8VVcP0rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age14kfkuvkflsntqyr57zc3gkh2r9szx3qy7swyvjtxxddzhsq47shs973gls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCaTJzcmthOGFmM1dDT3VJ
            RGx0TWQ4Nmh1b3lUUURRYnNHN3RjZ2N0U21jCmVEVWxFVkw2dHhKNkh4TWhtZDBN
            SDFnS3hkOVJIaVZGdTI1YTdZK0xPZjgKLS0tIHBjN1BxYVJlUDU3REF1OGQ3MUFh
            QzlFNzg4Rzk1aEdTS0h0M0c5Q1ZrM3MKS/FE4pGX7eEHxFZk+9pjcsb4s3IVPr3T
            0l13mpWBC80jnPwAeNjMPxSgb9/FsazGwcEdlmYKo5tyZIYMFKml+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T19:20:45Z"
    mac: ENC[AES256_GCM,data:cIERAXMWaJly8RR3Gs+/0Uyz3TUdz9mgcPfbWRFybWax4EEEEUWhZsrsqsefrgHawXf4NT5aAyjjrYdkj1CrwQ4sZMzC4io+FTtmH0oH1dAuVInTrLZfnwog+WiLNOrfS0YMpHfy8pCoD+VRvp2HQ0RGjP2qSH5K0DkjksiTmfA=,iv:t/A0Q01G0nSA+nvCYkSamRzARFqMEfXzD521jLLeIsM=,tag:TPiakxbz40b2Cdk1m2EgeA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.1
