apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskapp
  template:
    metadata:
      labels:
        app: taskapp
    spec:
      containers:
        - name: taskapp
          image: tasklist-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
