apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BHTS-QuadOps/gitops-repo
    targetRevision: main
    path: apps/postgres
    plugin:
      name: sops-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: postgres-secret
      namespace: postgres
      jsonPointers:
        - /data
        - /stringData
        - /sops