apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BHTS-QuadOps/gitops-repo
    targetRevision: main
    path: apps/taskapp
    plugin:
      name: sops-kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: taskapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
  - group: ""
    kind: Secret
    name: taskapp-secret
    jsonPointers:
      - /data
      - /stringData
