apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BHTS-QuadOps/gitops-repo
    path: apps/taskapp   
    targetRevision: main
    directory:
      recurse: true
    plugin:
      name: sops-v1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: taskapp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true