apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskapp
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BHTS-QuadOps/gitops-repo.git
    targetRevision: sisonke   # or staging/main depending on branch
    path: apps/taskapp
  destination:
    server: https://kubernetes.default.svc
    namespace: sisonke
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
